# Generated by Django 5.2 on 2025-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_level',
            field=models.CharField(choices=[('super', 'Super Admin'), ('department', 'Department Admin'), ('facility', 'Facility Admin')], default='facility', max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='managed_facilities',
            field=models.ManyToManyField(blank=True, related_name='managing_admins', to='reservation.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment_needed',
            field=models.TextField(blank=True, default='', help_text='List any equipment or setup needed'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting'), ('event', 'Event'), ('practice', 'Practice'), ('other', 'Other')], default='meeting', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requirements',
            field=models.TextField(blank=True, default='', help_text='Any special requirements or arrangements'),
        ),
        migrations.AddField(
            model_name='room',
            name='booking_rules',
            field=models.TextField(blank=True, help_text='Special rules or restrictions for booking'),
        ),
        migrations.AddField(
            model_name='room',
            name='facility_type',
            field=models.CharField(choices=[('function_hall', 'Function Hall'), ('pe_room', 'PE Room'), ('conference_room', 'Conference Room'), ('classroom', 'Classroom'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='max_booking_duration',
            field=models.DurationField(default='1:00:00', help_text='Maximum duration for a single booking'),
        ),
        migrations.AddField(
            model_name='room',
            name='operating_hours_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='room',
            name='operating_hours_start',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
