# Generated by Django 5.2 on 2025-05-11 15:02

import django.core.validators
import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_admin_admin_level_admin_managed_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='User profile photo. Only JPG, JPEG, PNG, and WebP files less than 2MB are allowed.', null=True, upload_to=reservation.models.user_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), reservation.models.validate_image_size]),
        ),
    ]
